[book]
authors = ["Lumière Élevé"]
language = "en"
multilingual = false
src = "src"
title = "Lightingale Docs"
description = "The master documentation of the Lightingale Community."

[build]
build-dir = "book"

[output.html]
site-url = "/"
default-theme = "coal"
preferred-dark-theme = "ayu"